apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "im-group.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "im-group.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
      - networking.k8s.io
    resources:
      - serviceaccounts
      - configmaps
      - secrets
      - statefulsets
      - deployments
      - services
      - ingresses
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update

  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - create
      - patch
      - delete

# Restart an instance
  - apiGroups:
      - apps
    resources:
      - deployments/scale
      - statefulsets/scale
    verbs:
      - get
      - update

# PgAdmin
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - create
      - delete

  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - create
      - delete
