apiVersion: skaffold/v2beta25
kind: Config
deploy:
  helm:
    releases:
      - name: im-group-whoami-test # Make sure this name isn't used by an already installed chart since that would overwrite the role
        namespace: whoami          # Name of namespace which the instance manager should be allowed to deploy to
        createNamespace: true
        chartPath: charts/im-group
        setValues:
          serviceAccount:
            name: im-manager-dev
            namespace: instance-manager-dev
