apiVersion: skaffold/v2beta25
kind: Config
deploy:
  helm:
    releases:
      - name: im-group-whoami
        namespace: whoami
        createNamespace: true
        chartPath: charts/im-group
#        valuesFiles:
#          - charts/core/values/dhis2.yaml
