# Default values for im-group.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

#serviceAccount:
#  name: name-of-service-account
#  namespace: namespace-of-service-account
